### ISSUE TITLE
Cloudflare Zaraz beta ignoring blocking triggers

### ISSUE THREAD

**Issue by CFranklinEvo** [managed-components/google-analytics-4#10]
Hi @bjesus ,

We have a few sites set up in Cloudflare Zaraz with essentially the same blocking triggers based on cookie values.
The configuration is the same across the board for multiple working sites and I have simplified the failing config down to just using GA4, no e-commerce, just PageView events, etc. and we're still seeing all of the GA4 cookies load despite the service being blocked.

Blocking Trigger used: Match rule, Cookie: cookie_analytics, Not matches regex, [1]
Expected outcome: GA4 cookies are not loaded unless cookie_analytics is set and equals '1'
Actual outcome: GA4 cookies load before `__cf_bm` cookie

The only difference that we've been able to see between the domains configured in Cloudflare is that the broken one has Zaraz flagged as a beta version. The working domains do not have the beta flag.

**Comment by aran112000** [comment]
Also seeing the same issue here

**Comment by bjesus** [comment]
Thanks, we can reproduce. In terms of this component, @simonabadoiu will make sure we only attach client-side events upon a pageview, which should fix this problem.

**Comment by aran112000** [comment]
Amazing, thank you

**Comment by bjesus** [comment]
Issue should be fixed

**Comment by CFranklinEvo** [comment]
Can confirm that's fixed the issue. Thanks a lot <3
