### ISSUE TITLE
Zaraz doesn't support the `add_contact_info` event

### ISSUE THREAD

**Issue by nick-potts** [managed-components/google-analytics-4#18]
I realise this is more of a Zaraz issue than a GA4 one, but `add_contact_info` is a pretty typical GA4 ecommerce event that currently isn't supported

**Comment by jonnyparris** [comment]
Zaraz ecommerce api is designed with the most common tracking parameters across all tools in mind; but indeed this repo is out of scope for that chat. Feel free to further the discussion on the Zaraz Discord channel or Cloudflare community forum if you're having specific trouble accessing particular fields there.
