### ISSUE TITLE
Set user properties

### ISSUE THREAD

**Issue by kadu-de-carvalho** [managed-components/google-analytics-4#20]
It is important for some projects have the possibility to set user properties.

Zaraz send user properties prefixed with _**ep**_ but user property in the URL needs to be prefixed with _**up**_ instead of _**ep**_.

Exemple: https://www.google-analytics.com/g/collect?[...]&up.user_subscription_type=premium

**Comment by tomkln** [comment]
Hi, thank you for your report. I'm going to investigate this shortly.

**Comment by tomkln** [comment]
I've just checked the code, as well as tried to replicate this issue on a test zone. 

When adding user properties, please make sure to manually specify the `up.` prefix to the data you send. This component will then automatically remove the `ep.` prefix and use the `up.` prefix instead.

You can find the related part of this components code here: https://github.com/managed-components/google-analytics-4/blob/main/src/requestBuilder.ts#L145

Here's an example when using Zaraz in the Cloudflare Dashboard:

---

<img width="1032" alt="image" src="https://github.com/managed-components/google-analytics-4/assets/21014430/37e2a114-b879-469c-9ea2-dc66748018b3">

---

<img width="1032" alt="image" src="https://github.com/managed-components/google-analytics-4/assets/21014430/99ce5cc3-f047-43e9-a10e-d81da11c9f2e">

---

As far as I understand it, these user prefixes can have any custom name, so it's difficult for us to choose automatically. If you have any suggestions on how to detect that and use-cases that require an automatic detection, please let us know and we might look further into it.

For now, it seems to me like a won't fix though. Please feel free to correct me :)

Hope this helps
